### ISSUE TITLE
lammps not handling angle_style none

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#175]
Running including 

lammps/unit_tests/angle_style-none/angle_style-none-data.input

results in 

INFO 2015-08-02 19:29:41 Converting angle_style-none-data
Traceback (most recent call last):
  File "test_lammps.py", line 155, in <module>
    test_lammps_unit(args['compute_energies'])
  File "test_lammps.py", line 41, in test_lammps_unit
    _run_lammps_and_compare(flags, test_tolerance=1e-4, test_type='unit')
  File "test_lammps.py", line 61, in _run_lammps_and_compare
    results = _convert_from_lammps(flags, test_type=test_type)
  File "test_lammps.py", line 130, in _convert_from_lammps
    diff = convert.main(flags)
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/convert.py", line 123, in main
    system = lammps_driver.read_file(in_file=lammps_file)
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/lammps/lammps_driver.py", line 15, in read_file
    system = load_lammps(in_file)
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/lammps/lammps_parser.py", line 31, in load_lammps
    return parser.read()
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/lammps/lammps_parser.py", line 312, in read
    self.read_data(self.data_file)
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/lammps/lammps_parser.py", line 413, in read_data
    parsable_keywords[keyword](data_lines)
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/lammps/lammps_parser.py", line 676, in parse_angle_coeffs
    self.lammps_angles, self.canonical_angle)
  File "/Users/mrshirts/work/papers/MMTOOLS/InterMol/intermol/lammps/lammps_parser.py", line 653, in parse_force_coeffs
    force_class = lammps_forces[style]
KeyError: 'none'

The dictionary in question is:

    lammps_angles = {
        'harmonic': HarmonicAngle,
        'cosine': CosineAngle,
        'cosine/squared': CosineSquaredAngle,
        'charmm': UreyBradleyAngle
        }

**Comment by mrshirts** [comment]
Any thoughts on the right way to solve this?   I think this might be the last "doesn't run" bug left.

**Comment by ctk3b** [comment]
This test is not a valid LAMMPS input file. Not quite sure what it is intended to test. We could remove all of the angles and angle coeffs from it...?

**Comment by mrshirts** [comment]
Hmm.  Strange.  Wonder what was working before.  I suppose we can remove it for now, though it would be good to figure out why it was running earlier -- maybe it got modified at some point?  

Looked back a little bit, couldn't figure out the history (was in a different branch). So I guess get rid of these for now?  We will have to think about more unit tests moving forward, however.

**Comment by mrshirts** [comment]
Tests removed in #190
