### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by Marcela51** [shirtsgroup/InterMol#284]
First, I am explaining how I installed InterMol and ParmEd, and the error message that I am getting is at the end of the message. No idea what I am doing wrong, thanks a lot, Marcela

I did the following:

```bash
module load python/2.7.8
pip install --editable .
```

Got:

```bash
Obtaining file:///usr/local/packages/InterMol
  Running setup.py (path:/usr/local/packages/InterMol/setup.py) egg_info for package from file:///usr/local/packages/InterMol
    
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/packages/python/2.7.8/lib/python2.7/site-packages (from intermol==0.1.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): parmed in /usr/local/packages/python/2.7.8/lib/python2.7/site-packages/ParmEd-2.5.1-py2.7-linux-x86_64.egg (from intermol==0.1.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): simtk.units in /usr/local/packages/python/2.7.8/lib/python2.7/site-packages/simtk.units-0.1-py2.7.egg (from intermol==0.1.0.dev0)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/packages/python/2.7.8/lib/python2.7/site-packages/six-1.8.0-py2.7.egg (from intermol==0.1.0.dev0)
Installing collected packages: intermol
  Running setup.py develop for intermol
    
    Creating /usr/local/packages/python/2.7.8/lib/python2.7/site-packages/intermol.egg-link (link to .)
    Removing intermol 0.1.0.dev0 from easy-install.pth file
    Adding intermol 0.1.0.dev0 to easy-install.pth file
    
    Installed /usr/local/packages/InterMol
Successfully installed intermol
Cleaning up…
```

Then I typed:
```bash
[mmadrid@kollman0 2.7.8]$ git clone -b amber_vels https://git@github.com/ctk3b/ParmEd.git
Initialized empty Git repository in /usr/local/packages/python/2.7.8/ParmEd/.git/
remote: Counting objects: 18647, done.
remote: Compressing objects: 100% (15/15), done.
Receiving objects:  28% (5222/18647), 33.00 MiB | 2.55 MiB/s   
remote: Total 18647 (delta 6), reused 0 (delta 0), pack-reused 18632
Receiving objects: 100% (18647/18647), 88.69 MiB | 2.03 MiB/s, done.
Resolving deltas: 100% (13013/13013), done.

mmadrid@kollman0 2.7.8]$ cd ParmEd
pip install --editable .
```

I am getting the following error message:

```bash
python convert.py --amb_in solv.rst7 solv.prmtop --desmond
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
Traceback (most recent call last):
  File "convert.py", line 8, in <module>
    import parmed
  File "/usr/local/packages/python/2.7.8/ParmEd/parmed/__init__.py", line 18, in <module>
    __version__ = get_versions()['version']
  File "/usr/local/packages/python/2.7.8/ParmEd/parmed/_version.py", line 485, in get_versions
    pieces = git_pieces_from_vcs(cfg.tag_prefix, root, verbose)
  File "/usr/local/packages/python/2.7.8/ParmEd/parmed/_version.py", line 284, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by ctk3b** [comment]
Hmm that's pretty odd. Can you try commenting out these lines and just replace it with something like `__version__ = '2.6.1'`?

If that doesn't work, are you using [`conda`](https://www.continuum.io/downloads#linux) on your machine by any chance? I just tried creating a clean environment and installing everything from scratch which worked on my laptop:

```bash
conda create -y -n conversions python=2.7 numpy
source activate conversions

git clone -b amber_vels https://git@github.com/ctk3b/ParmEd.git
cd ParmEd
pip install -e .
cd ..

git clone https://github.com/shirtsgroup/InterMol.git
cd InterMol
pip install -e .

cd intermol/tests/amber/stress_tests/solv
python ../../../../convert.py --amb_in solv.{rst7,prmtop} --desmond
```

**Comment by Marcela51** [comment]
which lines should I comment out? 
No, I am not using conda.
thanks,

Marcela

**Comment by ctk3b** [comment]
Sorry, forgot to add the link. These lines:
https://github.com/ParmEd/ParmEd/blob/master/parmed/__init__.py#L17-L19

**Comment by ctk3b** [comment]
I believe this was resolved via email. Let us know if anything else is still unclear and I'll reopen!
