### ISSUE TITLE
Provide better error if gromacs .itp distributed with source are not found. 

### ISSUE THREAD

**Issue by mrshirts** [shirtsgroup/InterMol#286]
Currently, it says something like:

INFO 2016-11-21 17:07:14 Beginning InterMol conversion
    Traceback (most recent call last):
      File "convert.py", line 678, in <module>
	main()
      File "convert.py", line 172, in main
	system = gmx.load(top_in, gro_in)
      File "/home/mmadrid/InterMol/intermol/gromacs/gromacs_parser.py", line 38, in load
	return parser.read()
      File "/home/mmadrid/InterMol/intermol/gromacs/gromacs_parser.py", line 391, in read
	self.process_file(self.top_filename)
      File "/home/mmadrid/InterMol/intermol/gromacs/gromacs_parser.py", line 1064, in process_file
	self.process_line(top_filename, '{0} {1}'.format(append, line))
      File "/home/mmadrid/InterMol/intermol/gromacs/gromacs_parser.py", line 1102, in process_line
	raise GromacsError('Could not locate #include file: '+name)
    intermol.exceptions.GromacsError: Could not locate #include file: oplsaa.ff/forcefield.itp

Which is not as clear as it could be.

**Comment by mrshirts** [comment]
It would be better to say something like "Did you add the Gromacs share directory to 'GMXDATA', or something like that.
