### ISSUE TITLE
Desmond to gromacs

### ISSUE THREAD

**Issue by Dileepvijayan** [shirtsgroup/InterMol#333]
Hi,
I was trying to use intermol to convert my Desmond cms file to gromacs. The cms file (linked) was created with the OPLS_2005 force field, water type TIP3P, using Maestro2016-4. It's  a small protein-ligand complex and I removed all the water molecules before solvating.     
link to the cms file:
https://www.dropbox.com/s/9e2rktefrnvpese/desmond_setup_1-out.cms?dl=0
I kept getting this error:  

--------------------Error message------------------
    INFO 2017-05-16 12:29:02 Beginning InterMol conversion
    INFO 2017-05-16 12:29:02 InterMol is research software. If you make use of InterMol in scientific publications please cite the following reference:Shirts, M.R., Klein, C., Swails, J.M. et al. J Comput Aided Mol Des (2016). doi:10.1007/s10822-016-9977-1
    Traceback (most recent call last):  File "/data/vijayan/software/Python-2.7.6/lib/python2.7/site-packages/intermol/convert.py", line 807, in <module>    main()  
File "/data/vijayan/software/Python-2.7.6/lib/python2.7/site-packages/intermol/convert.py", line 226, in main    system, prefix = _load_desmond(cms_in=cms_in)  
File "/data/vijayan/software/Python-2.7.6/lib/python2.7/site-packages/intermol/convert.py", line 589, in _load_desmond    system = des.load(cms_file=cms_in)  
File "/data/vijayan/software/Python-2.7.6/lib/python2.7/site-packages/intermol/desmond/desmond_parser.py", line 39, in load    return parser.read()  
File "/data/vijayan/software/Python-2.7.6/lib/python2.7/site-packages/intermol/desmond/desmond_parser.py", line 1141, in read    self.load_ffio_block(molname, self.ffio_blockpos[i], self.fmct_blockpos[i+1]-1)  
File "/data/vijayan/software/Python-2.7.6/lib/python2.7/site-packages/intermol/desmond/desmond_parser.py", line 903, in load_ffio_block    self.sysDirective[type](*params)  
File "/data/vijayan/software/Python-2.7.6/lib/python2.7/site-packages/intermol/desmond/desmond_parser.py", line 793, in parse_constraints    dHH = float(split[8])
IndexError: list index out of range
-----------------End error message-----------------

**Comment by mrshirts** [comment]
Hi, Dileepvijayan-  Try the master branch now.  I think the commits that are in should fix it.  Note that when I ran with --energy, the gromacs run crashed, but that appears to be because of bad initial coordinates, not a translation error.  Let me know if there are still remaining errors after you look at the coordinates.

**Comment by Dileepvijayan** [comment]
Dear Dr Shirts


Thanks for the email.i will check with the initial coordinates. If that is
wrong how come Desmond produce the results? I will check one more time and
let you know about it. Thanks

Best regards


Dileep

On 24-May-2017 3:03 pm, "Michael Shirts" <notifications@github.com> wrote:

Hi, Dileepvijayan- Try the master branch now. I think the commits that are
in should fix it. Note that when I ran with --energy, the gromacs run
crashed, but that appears to be because of bad initial coordinates, not a
translation error. Let me know if there are still remaining errors after
you look at the coordinates.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shirtsgroup/InterMol/issues/333#issuecomment-303626312>,
or mute the thread
