### ISSUE TITLE
Issues with installing InterMol

### ISSUE THREAD

**Issue by yinglongmiao** [shirtsgroup/InterMol#340]
Hello,

I tried to install InterMol, but it kept giving me the following errors:

$ sudo apt-get install python-setuptools
$ sudo apt-get install python-dev

$ git clone https://github.com/shirtsgroup/InterMol.git
$ cd InterMol
$ sudo python setup.py install
...
Installed /usr/local/lib/python2.7/dist-packages/intermol-0.1.0.dev0-py2.7.egg
Processing dependencies for intermol==0.1.0.dev0
Searching for numpy
Reading https://pypi.python.org/simple/numpy/
Best match: numpy 1.13.3
Downloading https://pypi.python.org/packages/bf/2d/005e45738ab07a26e621c9c12dc97381f372e06678adf7dc3356a69b5960/numpy-1.13.3.zip#md5=300a6f0528122128ac07c6deb5c95917
Processing numpy-1.13.3.zip
Writing /tmp/easy_install-BnZHej/numpy-1.13.3/setup.cfg
Running numpy-1.13.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-BnZHej/numpy-1.13.3/egg-dist-tmp-ZvNl0h
Running from numpy source directory.
/tmp/easy_install-BnZHej/numpy-1.13.3/setup.py:367: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  run_build = parse_setuppy_commands()
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
/tmp/easy_install-BnZHej/numpy-1.13.3/numpy/distutils/system_info.py:572: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
/tmp/easy_install-BnZHej/numpy-1.13.3/numpy/distutils/system_info.py:572: UserWarning: 
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  self.calc_info()
/tmp/easy_install-BnZHej/numpy-1.13.3/numpy/distutils/system_info.py:572: UserWarning: 
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  self.calc_info()
/bin/sh: 1: svnversion: not found
non-existing path in 'numpy/distutils': 'site.cfg'
/bin/sh: 1: svnversion: not found
/tmp/easy_install-BnZHej/numpy-1.13.3/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
/tmp/easy_install-BnZHej/numpy-1.13.3/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
 int exp (void);
     ^
_configtest.o: In function `main':
/tmp/easy_install-BnZHej/numpy-1.13.3/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.o: In function `main':
/tmp/easy_install-BnZHej/numpy-1.13.3/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
 int exp (void);
     ^
_configtest.c:1:24: fatal error: sys/endian.h: No such file or directory
compilation terminated.
_configtest.c:1:24: fatal error: sys/endian.h: No such file or directory
compilation terminated.
…

#ifndef _NPY_NPY_CONFIG_H_
#error config.h should never be included directly, include npy_config.h instead
#endif

EOF
_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
 int exp (void);
     ^
_configtest.o: In function `main':
/tmp/easy_install-BnZHej/numpy-1.13.3/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.o: In function `main':
/tmp/easy_install-BnZHej/numpy-1.13.3/_configtest.c:6: undefined reference to `exp'
collect2: error: ld returned 1 exit status
_configtest.c:1:5: warning: conflicting types for built-in function ‘exp’
 int exp (void);
     ^
_configtest.c:3:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 main()
 ^
…
Installed /usr/local/lib/python2.7/dist-packages/numpy-1.13.3-py2.7-linux-x86_64.egg
Searching for six==1.11.0
Best match: six 1.11.0
Processing six-1.11.0-py2.7.egg
six 1.11.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/six-1.11.0-py2.7.egg
Searching for ParmEd==2.7.3
Best match: ParmEd 2.7.3
Processing ParmEd-2.7.3-py2.7.egg
ParmEd 2.7.3 is already the active version in easy-install.pth
Installing parmed script to /usr/local/bin
Installing xparmed script to /usr/local/bin

Using /usr/local/lib/python2.7/dist-packages/ParmEd-2.7.3-py2.7.egg
Finished processing dependencies for intermol==0.1.0.dev0

miao01:~/programs/InterMol$ python test_gromacs.py --type unit
python: can't open file 'test_gromacs.py': [Errno 2] No such file or directory
====

Similar error was found for the convert.py. Would you have any suggestions?

Thanks,
Yinglong

**Comment by ctk3b** [comment]
There is no file called `test_gromacs.py`. Check out the testing directory for more info: https://github.com/shirtsgroup/InterMol/tree/master/intermol/tests

P.S.: It's generally not a good idea to `sudo pip install` since this could execute arbitrary code buried in the `setup.py`

**Comment by yinglongmiao** [comment]
Thanks for your reply, Christoph.

I have re-installed the package without sudo, but with the —user option. Also it runs fine with py.test -v.

Now I’m wondering whether we can convert maestro files as used by the DE Shaw’s group into the Amber .prmtop and .crd format with InterMol. What command(s) do we need for that?

All the best,
Yinglong

Yinglong Miao, Ph.D.
Assistant Professor
Center for Computational Biology and
Department of Molecular Biosciences
University of Kansas
2030 Becker Drive, Suite 200D MRB
Lawrence, KS 66047
miao@ku.edu<mailto:miao@ku.edu>; 785-864-8298 (office)
http://miao.compbio.ku.edu

On Oct 9, 2017, at 10:44 AM, Christoph Klein <notifications@github.com<mailto:notifications@github.com>> wrote:


There is no file called test_gromacs.py. Check out the testing directory for more info: https://github.com/shirtsgroup/InterMol/tree/master/intermol/tests

P.S.: It's generally not a good idea to sudo pip install since this could execute arbitrary code buried in the setup.py

**Comment by ctk3b** [comment]
We have basic support for the `.cms` file format. Check out the [readme](https://github.com/shirtsgroup/InterMol/blob/master/README.md) for basic instructions and let us know if you have any specific questions!

**Comment by yinglongmiao** [comment]
Just found an error as follows:


python convert.py --des_in tests/desmond/stress_tests/2BP4_amber99_bulk/2BP4_amber99_bulk.cms --amber
INFO 2017-10-10 17:05:31 Beginning InterMol conversion

INFO 2017-10-10 17:05:31 InterMol is research software. If you make use of InterMol in scientific publications please cite the following reference:
Shirts, M.R., Klein, C., Swails, J.M. et al. J Comput Aided Mol Des (2016). doi:10.1007/s10822-016-9977-1

ERROR 2017-10-10 17:05:32 nrexcl 0 not currently supported
Traceback (most recent call last):
  File "convert.py", line 663, in _save_amber
    top = pmd.load_file(oname + '.top', xyz=oname + '.gro')
  File "/usr/local/lib/python2.7/dist-packages/ParmEd-2.7.3-py2.7.egg/parmed/formats/registry.py", line 214, in load_file
    return cls(filename, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ParmEd-2.7.3-py2.7.egg/parmed/gromacs/gromacstop.py", line 247, in __init__
    self.read(fname, defines, parametrize)
  File "/usr/local/lib/python2.7/dist-packages/ParmEd-2.7.3-py2.7.egg/parmed/gromacs/gromacstop.py", line 435, in read
    GromacsWarning)
GromacsWarning: nrexcl 0 not currently supported
INFO 2017-10-10 17:05:32 Finished!


________________________________

**Comment by mrshirts** [comment]
Can you upload an example file that it fails on?  Much easier to debug that way!

**Comment by yinglongmiao** [comment]
Hi Michael,

The file was “InterMol/intermol/tests/desmond/stress_tests/2BP4_amber99_bulk/2BP4_amber99_bulk.cms”, a test Desmond file I found within the InterMol package.

Eventually, I would like to convert the maestro files used by the DE Shaw’s group for their Anton simulations (available here: http://pubs.acs.org/doi/suppl/10.1021/acs.jctc.7b00172) to the Amber format if it’s possible ...

Thanks!
Yinglong


On Oct 12, 2017, at 11:57 PM, Michael Shirts <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you upload an example file that it fails on? Much easier to debug that way!

**Comment by mrshirts** [comment]
I'll look into converting that over the weekend.

That particular file was converted from amber to desmond and back if I recall.  It would be useful if you tried to do a conversion of a file you were actually interested in which is Desmond native.  It might work.

OF course, we want to fix the bug, but making sure it works for your usage is the first priority.

**Comment by yinglongmiao** [comment]
Then it would be wonderful if we can make InterMol work for the maestro files you can download at: http://pubs.acs.org/doi/suppl/10.1021/acs.jctc.7b00172

Right now, I run into the following error:

python convert.py --des_in dmso.mae --amber
INFO 2017-10-12 22:24:03 Beginning InterMol conversion

INFO 2017-10-12 22:24:03 InterMol is research software. If you make use of InterMol in scientific publications please cite the following reference:
Shirts, M.R., Klein, C., Swails, J.M. et al. J Comput Aided Mol Des (2016). doi:10.1007/s10822-016-9977-1

Traceback (most recent call last):
  File "convert.py", line 811, in <module>
    main()
  File "convert.py", line 226, in main
    system, prefix = _load_desmond(cms_in=cms_in)
  File "convert.py", line 589, in _load_desmond
    system = des.load(cms_file=cms_in)
  File "/home/y147m353/.local/lib/python2.7/site-packages/intermol-0.1.0.dev0-py2.7.egg/intermol/desmond/desmond_parser.py", line 39, in load
    return parser.read()
  File "/home/y147m353/.local/lib/python2.7/site-packages/intermol-0.1.0.dev0-py2.7.egg/intermol/desmond/desmond_parser.py", line 1133, in read
    while ':::' not in self.lines[j]:
IndexError: list index out of range

Thanks,
Yinglong

On Oct 13, 2017, at 10:21 PM, Michael Shirts <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll look into converting that over the weekend.

That particular file was converted from amber to desmond and back if I recall. It would be useful if you tried to do a conversion of a file you were actually interested in which is Desmond native. It might work.

OF course, we want to fix the bug, but making sure it works for your usage is the first priority.

**Comment by mrshirts** [comment]
OK, I've downloaded that one.  Lots of grant writing this weekend, so if I can't get it to work with a bit of a tweak, it might take a while.

**Comment by yinglongmiao** [comment]
Sure, thanks a lot!


On Oct 13, 2017, at 10:41 PM, Michael Shirts <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I've downloaded that one. Lots of grant writing this weekend, so if I can't get it to work with a bit of a tweak, it might take a while.

**Comment by yinglongmiao** [comment]
Michael, hope all went well with your grant writing!

Any good news on converting the file?

Thanks,
Yinglong


On Oct 13, 2017, at 10:41 PM, Michael Shirts <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I've downloaded that one. Lots of grant writing this weekend, so if I can't get it to work with a bit of a tweak, it might take a while.

**Comment by mrshirts** [comment]
Not done yet, hopefully tomorrow. Apologies.

**Comment by yinglongmiao** [comment]
Thanks for the update, Michael. I have been waiting for converting these files so that we can start running the simulations here. Hope it’s not too much effort for the coding … ;-)

On Oct 26, 2017, at 2:41 AM, Michael Shirts <notifications@github.com<mailto:notifications@github.com>> wrote:


Not done yet, hopefully tomorrow. Apologies.

**Comment by mrshirts** [comment]
Hi, yinglong-

I think I have a workaround for now.  The problem is actually ParmEd, because the number of atoms to exclude is not properly being sent to the GROMACS file. 

The workaround is: 
1) convert desmond to GROMACS.  This is actually what InterMol currently does anyway.  
2) manually fix the GROMACS files. Wherever you see an entry of form 

[ moleculetype ] 
molecule_name    0

Then change the 0 to 3 (which it should be for AMBER or GAFF).

3) Run GROMACS to AMBER. 

Let me know if that works.  I'll look at the code, but it might take a bit longer.

**Comment by yinglongmiao** [comment]
Hi Michael,


I tried your suggestion on the dmso.mae, but still get the error for converting to gromacs. This step worked for example .cms file included in the intermol/tests, but conversion to amber showed "TypeError: AmberParm does not support all of the parameters defined in the input Structure", and no output for Amber files.


I have attached the program log below. Any further suggestions for fixing dmso.mae and step 3 - conversion to Amber will be much appreciated!


Thanks,

Yinglong


-----

python  ~/programs/InterMol/intermol/convert.py --des_in dmso.mae --gromacs
INFO 2017-11-10 13:41:08 Beginning InterMol conversion

INFO 2017-11-10 13:41:08 InterMol is research software. If you make use of InterMol in scientific publications please cite the following reference:
Shirts, M.R., Klein, C., Swails, J.M. et al. J Comput Aided Mol Des (2016). doi:10.1007/s10822-016-9977-1

Traceback (most recent call last):
  File "/home/y147m353/programs/InterMol/intermol/convert.py", line 811, in <module>
    main()
  File "/home/y147m353/programs/InterMol/intermol/convert.py", line 226, in main
    system, prefix = _load_desmond(cms_in=cms_in)
  File "/home/y147m353/programs/InterMol/intermol/convert.py", line 589, in _load_desmond
    system = des.load(cms_file=cms_in)
  File "/home/y147m353/.local/lib/python2.7/site-packages/intermol-0.1.0.dev0-py2.7.egg/intermol/desmond/desmond_parser.py", line 39, in load
    return parser.read()
  File "/home/y147m353/.local/lib/python2.7/site-packages/intermol-0.1.0.dev0-py2.7.egg/intermol/desmond/desmond_parser.py", line 1133, in read
    while ':::' not in self.lines[j]:
IndexError: list index out of range

### Example test
!  ~/programs/InterMol/intermol/convert.py --des_in ~/programs/InterMol/intermol/tests/desmond/stress_tests/2BP4_amber99_bulk/2BP4_amber99_bulk.cms --gromacs
INFO 2017-11-10 13:27:57 Finished!

! vim 2BP4_amber99_bulk_converted.*
[ moleculetype ]
Molecule_1          3

!  ~/programs/InterMol/intermol/convert.py --gro_in 2BP4_amber99_bulk_converted.gro 2BP4_amber99_bulk_converted.top --amber
ERROR 2017-11-10 13:31:24 AmberParm does not support all of the parameters defined in the input Structure
Traceback (most recent call last):
  File "/home/y147m353/programs/InterMol/intermol/convert.py", line 664, in _save_amber
    top.save(oname + '.prmtop', overwrite=True)
  File "/usr/local/lib/python2.7/dist-packages/ParmEd-2.7.3-py2.7.egg/parmed/structure.py", line 1533, in save
    s = amber.AmberParm.from_structure(self)
  File "/usr/local/lib/python2.7/dist-packages/ParmEd-2.7.3-py2.7.egg/parmed/amber/_amberparm.py", line 326, in from_structure
    raise TypeError('AmberParm does not support all of the '
TypeError: AmberParm does not support all of the parameters defined in the input Structure
INFO 2017-11-10 13:31:24 Finished!



________________________________

**Comment by mrshirts** [comment]
For the parmed problem, this is an issue with the ParmEd libraries that InterMol uses to convert from GROMACS to AMBER - it simply can't take all representations of dihedrals.  However, I know that they were looking to resolve this issue.  Your best bet is to check with ParmEd and see if the have resolved this issue.   I will check the dmso.cms problem.

**Comment by yinglongmiao** [comment]
Hi Michael,

That sounds good. Please let me know when you find a solution to the dmso.cms problem. I will also check with the latest version of ParmEd regarding the conversion from GROMACS to AMBER …

Thanks,
Yinglong


Yinglong Miao, Ph.D.
Assistant Professor
Center for Computational Biology and
Department of Molecular Biosciences
University of Kansas
http://miao.compbio.ku.edu

On Nov 13, 2017, at 12:33 AM, Michael Shirts <notifications@github.com<mailto:notifications@github.com>> wrote:


For the parmed problem, this is an issue with the ParmEd libraries that InterMol uses to convert from GROMACS to AMBER - it simply can't take all representations of dihedrals. However, I know that they were looking to resolve this issue. Your best bet is to check with ParmEd and see if the have resolved this issue. I will check the dmso.cms problem.

**Comment by mrshirts** [comment]
I have confirmed the error: something to do with the way the blocks are set
up in this particular MAE file.  It will take a bit of time to fix
correctly.

**Comment by yinglongmiao** [comment]
Can we perhaps check with Albert Pan to see how they came up this different version of MAE file, and is there a way to generate a file that’s compatible with InterMol? Thanks!

On Nov 13, 2017, at 9:50 AM, Michael Shirts <notifications@github.com<mailto:notifications@github.com>> wrote:

I have confirmed the error: something to do with the way the blocks are set
up in this particular MAE file. It will take a bit of time to fix
correctly.
