### ISSUE TITLE
Desmond to GMX

### ISSUE THREAD

**Issue by billy-noonan** [shirtsgroup/InterMol#341]
Hi All,

I have a system consisting of a protein-ligand complex in 150 mM NaCl solvent.  When I run MD on this system using Desmond, everything runs smoothly.  When I try to use convert.py using InterMol to convert the Desmond coordinates to Gromacs with:

**mkdir gmx

python ~/InterMol-master/intermol/convert.py --des_in 1_MD_gmx.cms --gromacs --odir gmx --energy**

I receive the following error, which I presume has something to do with the .cms file:

 **File "/vcp2/student/billy/InterMol-master/intermol/convert.py", line 811, in <module>
    main()
  File "/vcp2/student/billy/InterMol-master/intermol/convert.py", line 226, in main
    system, prefix = _load_desmond(cms_in=cms_in)
  File "/vcp2/student/billy/InterMol-master/intermol/convert.py", line 589, in _load_desmond
    system = des.load(cms_file=cms_in)
  File "/vcp2/student/billy/anaconda3/lib/python3.6/site-packages/intermol-0.1.0.dev0-py3.6.egg/intermol/desmond/desmond_parser.py", line 39, in load
    return parser.read()
  File "/vcp2/student/billy/anaconda3/lib/python3.6/site-packages/intermol-0.1.0.dev0-py3.6.egg/intermol/desmond/desmond_parser.py", line 1079, in read
    with open(self.cms_file, 'r') as fl:**

When I use a system consisting of a cyclic peptide in chloroform, I don't get this error...

Please advise?

Cheers,

Billy

**Comment by ctk3b** [comment]
Hi Billy, looks like the last bit of the traceback got chopped off. Could you post the full error message? Also if possible, can you share the input files? That makes it significantly easier for us to debug.

**Comment by billy-noonan** [comment]
Hi ctk3b,

I am unable to send you the .cms file for the entire system, however I have included here the coordinates for the protein alone in solvent. 

When running the following command:

**python ~/InterMol-master/intermol/convert.py --des_in protein_MD.cms --gromacs --odir gmx --energy**

I get this error:

**^CFailed to import the site module
Traceback (most recent call last):
  File "/vcp2/student/billy/anaconda3/lib/python3.6/site.py", line 544, in <module>
    main()
  File "/vcp2/student/billy/anaconda3/lib/python3.6/site.py", line 537, in main
    execsitecustomize()
  File "/vcp2/student/billy/anaconda3/lib/python3.6/site.py", line 481, in execsitecustomize
    import sitecustomize
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 946, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 885, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1245, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1285, in _fill_cache
KeyboardInterrupt
billy@eta:~/Documents/SPSB/sim015/protein_MD> mkdir gmx
billy@eta:~/Documents/SPSB/sim015/protein_MD> python ~/InterMol-master/intermol/convert.py --des_in protein_MD.cms --gromacs --odir gmx --energy
INFO 2017-11-01 17:04:52 Beginning InterMol conversion

INFO 2017-11-01 17:04:52 InterMol is research software. If you make use of InterMol in scientific publications please cite the following reference:
Shirts, M.R., Klein, C., Swails, J.M. et al. J Comput Aided Mol Des (2016). doi:10.1007/s10822-016-9977-1

Traceback (most recent call last):
  File "/vcp2/student/billy/InterMol-master/intermol/convert.py", line 811, in <module>
    main()
  File "/vcp2/student/billy/InterMol-master/intermol/convert.py", line 226, in main
    system, prefix = _load_desmond(cms_in=cms_in)
  File "/vcp2/student/billy/InterMol-master/intermol/convert.py", line 589, in _load_desmond
    system = des.load(cms_file=cms_in)
  File "/vcp2/student/billy/anaconda3/lib/python3.6/site-packages/intermol-0.1.0.dev0-py3.6.egg/intermol/desmond/desmond_parser.py", line 39, in load
    return parser.read()
  File "/vcp2/student/billy/anaconda3/lib/python3.6/site-packages/intermol-0.1.0.dev0-py3.6.egg/intermol/desmond/desmond_parser.py", line 1141, in read
    self.load_ffio_block(molname, self.ffio_blockpos[i], self.fmct_blockpos[i+1]-1)
  File "/vcp2/student/billy/anaconda3/lib/python3.6/site-packages/intermol-0.1.0.dev0-py3.6.egg/intermol/desmond/desmond_parser.py", line 903, in load_ffio_block
    self.sysDirective[type](*params)
  File "/vcp2/student/billy/anaconda3/lib/python3.6/site-packages/intermol-0.1.0.dev0-py3.6.egg/intermol/desmond/desmond_parser.py", line 576, in parse_bonds
    new_bond = self.create_forcetype(self.desmond_bonds[key], atoms, params)
KeyError: 'INVALID'**



If you send me an e-mail, I'll send you the .cms file attached.

Thanks again for the help!

Cheers,

Billy

**Comment by camposgavy** [comment]
When you encounter KeyError: 'INVALID', you have  "INVALID" as a keyword in your .cms file. Please review the input and ensure it is in the correct format.
