### ISSUE TITLE
Desmond conversion

### ISSUE THREAD

**Issue by tjgdamen** [shirtsgroup/InterMol#344]
When I try to convert a Desmond .cms file to any other format I get the following error:

Traceback (most recent call last):
  File "convert.py", line 811, in <module>
    main()
  File "convert.py", line 226, in main
    system, prefix = _load_desmond(cms_in=cms_in)
  File "convert.py", line 589, in _load_desmond
    system = des.load(cms_file=cms_in)
  File "C:\ProgramData\PyMOL\lib\site-packages\intermol-0.1.0.dev0-py2.7.egg\intermol\desmond\desmond_parser.py", line 39, in load
    return parser.read()
  File "C:\ProgramData\PyMOL\lib\site-packages\intermol-0.1.0.dev0-py2.7.egg\intermol\desmond\desmond_parser.py", line 1141, in read
    self.load_ffio_block(molname, self.ffio_blockpos[i], self.fmct_blockpos[i+1]-1)
  File "C:\ProgramData\PyMOL\lib\site-packages\intermol-0.1.0.dev0-py2.7.egg\intermol\desmond\desmond_parser.py", line 903, in load_ffio_block
    self.sysDirective[type](*params)
  File "C:\ProgramData\PyMOL\lib\site-packages\intermol-0.1.0.dev0-py2.7.egg\intermol\desmond\desmond_parser.py", line 576, in parse_bonds
    new_bond = self.create_forcetype(self.desmond_bonds[key], atoms, params)
KeyError: 'INVALID'

I have read several topics with seem to have similar issues, but never found a solution for this error.

Thanks in advance for helping me out.

**Comment by mrshirts** [comment]
I can try to take a look, if you could send an example file that fails (the smaller, the better).

**Comment by shansun7994** [comment]
I ran into the same problem. Do we have a solution now?

**Comment by mehdim390** [comment]
Dear all,

Any solution for this issue with Maestro (Schrodinger Suite 2018-1) ?

**Comment by mrshirts** [comment]
I apologize for the lack of response.  We unfortunately don't have the manpower in the lab to bugfix this semester.

**Comment by Thuravi** [comment]
Dear Mr. Shirts,

Is there any updates on this? I am still facing the same error. 
It would be really helpful if you could reply regarding this issue.
Thanks in advance.

Best,
Santhosh
