### ISSUE TITLE
UnboundLocalError: local variable 'npermol' referenced before assignment

### ISSUE THREAD

**Issue by phenylazide** [shirtsgroup/InterMol#352]
python convert.py --des_in desmond_md_job_2.cms --gromacs --odir yyy -e
INFO 2018-12-20 10:00:02 Beginning InterMol conversion

INFO 2018-12-20 10:00:02 InterMol is research software. If you make use of InterMol in scientific publications please cite the following reference:
Shirts, M.R., Klein, C., Swails, J.M. et al. J Comput Aided Mol Des (2016). doi:10.1007/s10822-016-9977-1

Traceback (most recent call last):
  File "/home/phzd/test/InterMol-master/intermol/convert.py", line 811, in <module>
    main()
  File "/home/phzd/test/InterMol-master/intermol/convert.py", line 226, in main
    system, prefix = _load_desmond(cms_in=cms_in)
  File "/home/phzd/test/InterMol-master/intermol/convert.py", line 589, in _load_desmond
    system = des.load(cms_file=cms_in)
  File "/home/phzd/miniconda3/envs/python27/lib/python2.7/site-packages/intermol/desmond/desmond_parser.py", line 39, in load
    return parser.read()
  File "/home/phzd/miniconda3/envs/python27/lib/python2.7/site-packages/intermol/desmond/desmond_parser.py", line 1141, in read
    self.load_ffio_block(molname, self.ffio_blockpos[i], self.fmct_blockpos[i+1]-1)
  File "/home/phzd/miniconda3/envs/python27/lib/python2.7/site-packages/intermol/desmond/desmond_parser.py", line 903, in load_ffio_block
    self.sysDirective[type](*params)
  File "/home/phzd/miniconda3/envs/python27/lib/python2.7/site-packages/intermol/desmond/desmond_parser.py", line 563, in parse_bonds
    current_molecule_type.bond_forces = self.loadMBonds(self.lines, self.bond_blockpos[0], i, npermol)
UnboundLocalError: local variable 'npermol' referenced before assignment

**Comment by mrshirts** [comment]
I'n not sure we'll have a chance to look at it soon, but unless you upload the file that caused the problem, we have no chance of fixing it :)
