### ISSUE TITLE
Desmond to Prmtop 

### ISSUE THREAD

**Issue by amrhamedp** [shirtsgroup/InterMol#359]
Hello,
 I am trying to work with prmtop generated using Intermol from a desmond cms file (2018-4 opls2005). I tried to do energy minimization using amber but it will fail:

[desmond_setup_2-out.cms.zip](https://github.com/shirtsgroup/InterMol/files/3684255/desmond_setup_2-out.cms.zip)

| ERROR:   PMEMD does not support single H residues!
|          Atom number   4052, Residue number    516

During Intermol conversion, the debug messages show the following:
```
python ./InterMol/intermol/convert.py --des_in desmond_setup_2-out.cms --amber -v
INFO 2019-10-02 22:59:23 Beginning InterMol conversion

INFO 2019-10-02 22:59:23 InterMol is research software. If you make use of InterMol in scientific publications please cite the following reference:
Shirts, M.R., Klein, C., Swails, J.M. et al. J Comput Aided Mol Des (2016). doi:10.1007/s10822-016-9977-1

DEBUG 2019-10-02 22:59:23 Reading ffio block...
DEBUG 2019-10-02 22:59:23 Parsing [ molecule system - minimized ]
DEBUG 2019-10-02 22:59:23 Parsing [ ffio ]
DEBUG 2019-10-02 22:59:23 Parsing [ vdwtypes ] ...
DEBUG 2019-10-02 22:59:23 Parsing [ sites ] ...
DEBUG 2019-10-02 22:59:23 Parsing [ m_atom ] ...
DEBUG 2019-10-02 22:59:23    Parsing [ i_m_mmod_type ] ...
DEBUG 2019-10-02 22:59:23    Parsing [ r_m_x_coord ] ...
DEBUG 2019-10-02 22:59:23    Parsing [ r_m_y_coord ] ...
DEBUG 2019-10-02 22:59:23    Parsing [ r_m_z_coord ] ...
DEBUG 2019-10-02 22:59:23    Parsing [ i_m_residue_number ] ...
DEBUG 2019-10-02 22:59:23    Parsing [ s_m_pdb_residue_name ] ...
DEBUG 2019-10-02 22:59:23    Parsing [ s_m_pdb_atom_name ] ...
DEBUG 2019-10-02 22:59:23    Parsing [ i_m_atomic_number ] ...
DEBUG 2019-10-02 22:59:23    Parsing atoms...
DEBUG 2019-10-02 22:59:24 Parsing [ m_bonds ] ...
DEBUG 2019-10-02 22:59:24 Parsing [ bonds ]...
DEBUG 2019-10-02 22:59:26 Parsing [ angles ] ...
DEBUG 2019-10-02 22:59:32 Parsing [ dihedrals ] ...
DEBUG 2019-10-02 22:59:50 Parsing [ exclusions ] ...
DEBUG 2019-10-02 22:59:50 Parsing [ pairs ] ...
DEBUG 2019-10-02 23:00:03 Warning: Parsing [ restraints] not yet implemented
DEBUG 2019-10-02 23:00:03 Parsing [ constraints ] ...
DEBUG 2019-10-02 23:00:03 Parsing [ molecule Cl- ]
DEBUG 2019-10-02 23:00:03 Parsing [ ffio ]
DEBUG 2019-10-02 23:00:03 Parsing [ vdwtypes ] ...
DEBUG 2019-10-02 23:00:03 Parsing [ sites ] ...
DEBUG 2019-10-02 23:00:03 Parsing [ m_atom ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ i_m_mmod_type ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ r_m_x_coord ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ r_m_y_coord ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ r_m_z_coord ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ i_m_residue_number ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ s_m_pdb_residue_name ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ s_m_pdb_atom_name ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ i_m_atomic_number ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ s_m_atom_name ] ...
DEBUG 2019-10-02 23:00:03    Parsing atoms...
DEBUG 2019-10-02 23:00:03 Parsing [ bonds ]...
DEBUG 2019-10-02 23:00:03 Parsing [ angles ] ...
DEBUG 2019-10-02 23:00:03 Parsing [ dihedrals ] ...
DEBUG 2019-10-02 23:00:03 Parsing [ exclusions ] ...
DEBUG 2019-10-02 23:00:03 Parsing [ pairs ] ...
DEBUG 2019-10-02 23:00:03 Warning: Parsing [ restraints] not yet implemented
DEBUG 2019-10-02 23:00:03 Parsing [ constraints ] ...
DEBUG 2019-10-02 23:00:03 Parsing [ molecule SPC water box ]
DEBUG 2019-10-02 23:00:03 Parsing [ ffio ]
DEBUG 2019-10-02 23:00:03 Parsing [ vdwtypes ] ...
DEBUG 2019-10-02 23:00:03 Parsing [ sites ] ...
DEBUG 2019-10-02 23:00:03 Parsing [ m_atom ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ i_m_mmod_type ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ r_m_x_coord ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ r_m_y_coord ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ r_m_z_coord ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ i_m_residue_number ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ s_m_pdb_residue_name ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ s_m_pdb_atom_name ] ...
DEBUG 2019-10-02 23:00:03    Parsing [ i_m_atomic_number ] ...
DEBUG 2019-10-02 23:00:03    Parsing atoms...
DEBUG 2019-10-02 23:00:08 Parsing [ m_bonds ] ...
DEBUG 2019-10-02 23:00:08 Parsing [ bonds ]...
DEBUG 2019-10-02 23:00:08 Parsing [ angles ] ...
DEBUG 2019-10-02 23:00:08 Parsing [ dihedrals ] ...
DEBUG 2019-10-02 23:00:08 Parsing [ exclusions ] ...
DEBUG 2019-10-02 23:00:08 Parsing [ pairs ] ...
DEBUG 2019-10-02 23:00:08 Warning: Parsing [ restraints] not yet implemented
DEBUG 2019-10-02 23:00:08 Parsing [ constraints ] ...
DEBUG 2019-10-02 23:00:08 Reading Box Vector...
ERROR 2019-10-02 23:00:15 nrexcl 0 not currently supported
Traceback (most recent call last):
  File "./InterMol/intermol/convert.py", line 663, in _save_amber
    top = pmd.load_file(oname + '.top', xyz=oname + '.gro')
  File "/software/anaconda2/envs/intermol/lib/python3.6/site-packages/parmed/formats/registry.py", line 214, in load_file
    return cls(filename, *args, **kwargs)
  File "/software/anaconda2/envs/intermol/lib/python3.6/site-packages/parmed/gromacs/gromacstop.py", line 251, in __init__
    self.read(fname, defines, parametrize)
  File "/software/anaconda2/envs/intermol/lib/python3.6/site-packages/parmed/gromacs/gromacstop.py", line 445, in read
    GromacsWarning)
parmed.exceptions.GromacsWarning: nrexcl 0 not currently supported
INFO 2019-10-02 23:00:15 Finished!



```

**Comment by mrshirts** [comment]
What seems to be happening is that it's stopping on the .gro and .top files, and never producing the amber files, because it's unable to figure out the exclusion distance when converting from DESMOND.  I will need to address that bug eventually, but can't currently.

As a stopgap, you can:
* Take the GROMACS files, and 
    * delete the [exclusions] sections.
    * For all of the [ moleculetype] entries, change the '0' to '3' (I'm guessing).
* Run the resulting files through ParmEd (will need to look up the ParmEd syntax)

I'm not set up to test right now, but this, in theory should work.

**Comment by prajwal07** [comment]
Hi @mrshirts , 
Just curious to know if there is any update on the issue. 
I am also facing the same issue with same command to convert .cms file to AMBER format. 
Please let me know, 
@amrhamedp , Did you able to resolve the issue somehow? 
Thanks and best regards, 
-Prajwal

**Comment by mrshirts** [comment]
There probably isn't sufficient manpower to look into these issues right now, unfortunately, especially during the school year.  There might be the possibility of an InterMol upgrade/replacement at some point in the next year, but nothing certain yet.
