### ISSUE TITLE
Conversion DESMOND--> AMBER

### ISSUE THREAD

**Issue by icamps** [shirtsgroup/InterMol#365]
I would like to know how to make the conversion DESMOND-->AMBER.

From here, it is tell that the conversion will be DESMOND--> GROMACS --> AMBER.

Using the command:

`python convert.py --des_in ~/Documents/01_Sim1-ARB/desmond_md_Sim1-ARB-out.cms --amber --odir ~/Documents/AMBERFormat/01_Sim1-ARB/`

I am getting the message:

```
ERROR 2020-08-18 16:17:04 list index out of range
Traceback (most recent call last):
  File "convert.py", line 663, in _save_amber
    top = pmd.load_file(oname + '.top', xyz=oname + '.gro')
  File "/home/icamps/anaconda3/lib/python3.7/site-packages/parmed/formats/registry.py", line 214, in load_file
    return cls(filename, *args, **kwargs)
  File "/home/icamps/anaconda3/lib/python3.7/site-packages/parmed/gromacs/gromacstop.py", line 251, in __init__
    self.read(fname, defines, parametrize)
  File "/home/icamps/anaconda3/lib/python3.7/site-packages/parmed/gromacs/gromacstop.py", line 374, in read
    atoms = [molecule.atoms[int(w)-1] for w in line.split()]
  File "/home/icamps/anaconda3/lib/python3.7/site-packages/parmed/gromacs/gromacstop.py", line 374, in <listcomp>
    atoms = [molecule.atoms[int(w)-1] for w in line.split()]
IndexError: list index out of range
INFO 2020-08-18 16:17:04 Finished!
```

and two files are created:
```
desmond_md_Sim1-ARB-out_converted.top
desmond_md_Sim1-ARB-out_converted.gro
```

What I am doing wrong? I appreciate any help.

**Comment by mrshirts** [comment]
So, it's converting Desmond into GROMACS correctly, but not from GROMACS into AMBER. So there is probably something wrong with the GROMACS files. It's impossible to tell from here, though.  How many atoms are the .cms files?

**Comment by icamps** [comment]
In the .cms file are 25600 atoms.

**Comment by icamps** [comment]
Any ideas?

**Comment by mrshirts** [comment]
Do you have sample files?  It's hard to debug with out sample files to run
to replicate the error.

**Comment by icamps** [comment]
The files are too big (2.4GB) to share here. Please, you can download the DESMOND files from [https://bit.ly/3lBOYzY](https://bit.ly/3lBOYzY).
