### ISSUE TITLE
Error in converting cms to Gromacs topology

### ISSUE THREAD

**Issue by Moh-Pou** [shirtsgroup/InterMol#372]
Dear InterMol developers,

I get an error when converting the cms file to Gromacs, and I would appreciate it if you could help me resolve the issue. 

This is a link to the cms file:
https://drive.google.com/file/d/1kqiS1MXduum09GpD3jtezi36n2qtRz1a/view?usp=sharing

This is the command that I use:
python convert.py --des_in ~/Downloads/desmond_setup_SAH-out.cms  --gromacs --odir ~/Downloads/

This is the error message:

INFO 2020-11-18 21:43:38 Beginning InterMol conversion

INFO 2020-11-18 21:43:38 InterMol is research software. If you make use of InterMol in scientific publications please cite the following reference:
Shirts, M.R., Klein, C., Swails, J.M. et al. J Comput Aided Mol Des (2016). doi:10.1007/s10822-016-9977-1

Traceback (most recent call last):
  File "convert.py", line 811, in <module>
    main()
  File "convert.py", line 226, in main
    system, prefix = _load_desmond(cms_in=cms_in)
  File "convert.py", line 589, in _load_desmond
    system = des.load(cms_file=cms_in)
  File "/anaconda3/lib/python3.7/site-packages/intermol-0.1.0-py3.7.egg/intermol/desmond/desmond_parser.py", line 40, in load
    return parser.read()
  File "/anaconda3/lib/python3.7/site-packages/intermol-0.1.0-py3.7.egg/intermol/desmond/desmond_parser.py", line 1170, in read
    self.load_ffio_block(molname, self.ffio_blockpos[i], self.fmct_blockpos[i+1]-1)
  File "/anaconda3/lib/python3.7/site-packages/intermol-0.1.0-py3.7.egg/intermol/desmond/desmond_parser.py", line 925, in load_ffio_block
    self.sysDirective[type](*params)
  File "/anaconda3/lib/python3.7/site-packages/intermol-0.1.0-py3.7.egg/intermol/desmond/desmond_parser.py", line 579, in parse_bonds
    new_bond = self.create_forcetype(self.desmond_bonds[key], atoms, params)
KeyError: 'INVALID'

**Comment by Thuravi** [comment]
Dear Mr. Pourmousa,

I am currently facing the same issue. Is there any update regarding this? Could you able to solve this issue?

Best
Santhosh
