### ISSUE TITLE
issue with import intermol.gromacs .... SyntaxError

### ISSUE THREAD

**Issue by kishantchem** [shirtsgroup/InterMol#385]
nit-w@NITW:~/software/InterMol-master/new/InterMol/intermol$ python convert.py -h
Traceback (most recent call last):
  File "convert.py", line 13, in <module>
    import intermol.gromacs as gmx
  File "/usr/local/lib/python2.7/dist-packages/intermol-0.1.0-py2.7.egg/intermol/gromacs/__init__.py", line 112
    logger.error(f'grompp failed with error code {proc.returncode} See {stderr_path}')
                                                                                    ^
SyntaxError: invalid syntax

**Comment by kishantchem** [comment]
Issue Resolved: 
$ python3 convert.py
worked for me.
