### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by debanjansen48** [shirtsgroup/InterMol#388]
$ python2 convert.py -h
Traceback (most recent call last):
  File "convert.py", line 13, in <module>
    import intermol.gromacs as gmx
  File "/home/anaconda3/envs/intermol/lib/python2.7/site-packages/intermol/gromacs/__init__.py", line 112
    logger.error(f'grompp failed with error code {proc.returncode} See {stderr_path}')
                                                                                 ^
SyntaxError: invalid syntax

**Comment by mattwthompson** [comment]
Hi @debanjansen48 - Python 2 has been EOL since January 1, 2020 and is no longer supported I'm not sure what what point InterMol stopped supporting Python 2 but we can can only help with Python 3 code. Make sure you upgrade your scripts to Python 3 (ideally 3.8 or newer following NEP 29) and, while using conda environments, invoke python with an executable provided by the conda environment. (If you're not sure, run `which python` and look at the path to that executable.)
